<a href="https://colab.research.google.com/github/19pa1a05b5/NLP/blob/main/EXPERIMENT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Write a program to implement the Minimum Edit Distance algorithm using Python.**


In [1]:
#importing numpy library
import numpy as np

In [4]:
def min_edit_dist(S1, S2):
  len1, len2 = len(S1), len(S2)
  table = np.zeros((len1+1 , len2+1), dtype=int)

  for i in range(1,len1+1):
    table[i,0] = table[i-1, 0] + 1 #deleting (cost=1)
  for j in range(1,len2+1):
    table[0,i] = table[0,i-1] + 1 #inserting (cost=1)
  
  for i in range(1,len1+1):
    for j in range(1,len2+1):
      table[i, j] = min(
          table[i-1, j] + 1,
          table[i, j-1] + 1,
          table[i-1, j-1] if (S1[i-1]==S2[j-1]) else table[i-1, j-1]+2
          )
  print(table)
  return table[len1,len2]

source = "test"
target = "text"
print(f"Minimum Edit Distance between {source} and {target} is: {min_edit_dist(source, target)}")

[[0 0 0 0 1]
 [1 0 1 1 0]
 [2 1 0 1 1]
 [3 2 1 2 2]
 [4 3 2 3 2]]
Minimum Edit Distance between test and text is: 2
